// react/src/components/calendar/index.tsx
import React, {useState, useEffect, useContext} from 'react';
import moment from 'moment';
import {OrganizerContext, Week, Day } from '../shared/OrganizerProvider';
import './index.scss'

export const Calendar = () => {
    const { subject, changeDate, generate } = useContext<any>( OrganizerContext );
    const [calendar, setCalendar] = useState<Week[]>([]);
    const [subValue, setSubValue] = useState<moment.Moment>(subject.value);

    useEffect(()=>{
        subject.subscribe(setCalendar(generate(subValue)))
    }, [subValue])

    const select = (day: Day) => {
        if (!day.disabled) {
            changeDate(day.value)
            setSubValue(moment(day.value))
        }
    }

    return <table>
        <thead>
            <tr>
                <th>Sun</th>
                <th>Mon</th>
                <th>Tue</th>
                <th>Wen</th>
                <th>Thu</th>
                <th>Fri</th>
                <th>Sat</th>
            </tr>
        </thead>
        <tbody>
            {calendar.map((weeks, w)=>(
               <tr key={w}>
                   {weeks.days.map((day, d)=>(
                       <td key={d} className={`${day.selected?'selected':''} ${day.active?'active':''} ${day.disabled?'disabled':''}`} onClick={()=> select(day)}>
                         <span>{ moment(day.value).format('ddd DD')}</span>
                       </td>
                   ))}
              </tr>)
            )}
         </tbody>
    </table>
}

// angular/src/app/calendar/calendar.component.ts
import {Component, OnInit} from '@angular/core';
import * as moment from 'moment';
import {DateService} from '../shared/date.service';

interface Day {
  value: moment.Moment;
  active: boolean;
  disabled: boolean;
  selected: boolean;
}

interface Week {
  days: Day[];
}

@Component({
  selector: 'app-calendar',
  templateUrl: './calendar.component.html',
  styleUrls: ['./calendar.component.scss']
})
export class CalendarComponent implements OnInit {

  calendar: Week[];

  constructor(private dateService: DateService) {
  }

  ngOnInit() {
    this.dateService.date.subscribe(this.generate.bind(this));
  }

  generate(now: moment.Moment) {
    const startDay = now.clone().startOf('month').startOf('week');
    const endDay = now.clone().endOf('month').endOf('week');

    const date = startDay.clone().subtract(1, 'day');

    const calendar = [];

    while (date.isBefore(endDay, 'day')) {
      calendar.push({
        days: Array(7)
          .fill(0)
          .map(() => {
            const value = date.add(1, 'day').clone();
            const active = moment().isSame(value, 'date');
            const disabled = !now.isSame(value, 'month');
            const selected = now.isSame(value, 'date');

            return {
              value, active, disabled, selected
            };
          })
      });
    }

    this.calendar = calendar;
  }

  select(day: moment.Moment) {
    this.dateService.changeDate(day);
  }

}

<table>
  <thead>
  <tr>
    <th>Sun</th>
    <th>Mon</th>
    <th>Tue</th>
    <th>Wen</th>
    <th>Thu</th>
    <th>Fri</th>
    <th>Sat</th>
  </tr>
  </thead>

  <tbody>
  <tr *ngFor="let week of calendar">
    <td
      *ngFor="let day of week.days"
      [class.disabled]="day.disabled"
      [class.selected]="day.selected"
      [class.active]="day.active"
      (click)="select(day.value)"
    >
      <span>{{ day.value | moment:'ddd DD' }}</span>
    </td>
  </tr>
  </tbody>
</table>
